accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("signup/", views.create_user, name="signup"),
    path("profile/", views.Profile.as_view(), name="profile"),
    path("edit_profile/", views.UserEditView.as_view(), name="edit-profile"),
    path("delete_profile/", views.delete_user, name="delete-profile"),
]

app_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    NONE = ''

    SEX_CHOICES = [
        (NONE, ''),
        (MALE, 'Male'),
        (FEMALE, 'Female')
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, default=NONE, null=True, blank=True)
    city = models.CharField(max_length=55, blank=True, null=True)
    country = models.CharField(max_length=55, blank=True, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f"{self.user.username} profile"
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import UserProfile

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label="First name", max_length=55, widget=forms.TextInput(attrs={'class':'form-control '}))
    last_name = forms.CharField(label="Last name", max_length=55, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(label="Email", widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].label = 'Username'
        self.fields['username'].help_text = "" #'<span class="form-text text-muted"><small>This field is required.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].label = 'Password'
        self.fields['password1'].help_text = "" # '<ul class="form-text text-muted"><li><small>Your password must contain at least 8 characters.</small></li><li><small>Your password can\'t be entirely numeric.<small></li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].label = 'Retype password'
        self.fields['password2'].help_text = "" #'<span class="form-text text-muted"><small>Type your password as before, for verification.</small></span>'
    

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class UserProfileUpdateForm(forms.ModelForm):
    sex = forms.ChoiceField(choices=UserProfile.SEX_CHOICES, required=False)
    city = forms.CharField(required=False)
    country = forms.CharField(required=False)
    class Meta:
        model = UserProfile
        fields = ['image', 'sex', 'city', 'country']

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy

from .forms import SignUpForm, UserUpdateForm, UserProfileUpdateForm
from .models import User

class Profile(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'

class UserEditView(LoginRequiredMixin, UpdateView):
    form_class = UserUpdateForm
    template_name = 'registration/edit_profile.html'
    success_url = reverse_lazy('home')

    def get_object(self):
        return self.request.user
    
    def post(self, request):
        user = get_object_or_404(User, pk=request.user.id)
        u_form = UserUpdateForm(request.POST, instance=user)
        p_form = UserProfileUpdateForm(request.POST, request.FILES, instance=user.userprofile)
        if u_form.is_valid() and p_form.is_valid():
            if User.objects.exclude(id=request.user.id).filter(email=u_form.cleaned_data['email']):
                messages.error(request, "A user with this email already exist!")
                return render(request, 'registration/edit_profile.html', {'u_form':u_form, 'p_form': p_form })
            u_form.save()
            p_form.save()
            return redirect('profile')
        u_form = UserUpdateForm()
        p_form = UserProfileUpdateForm()
        return render(request, 'registration/edit_profile.html', {'u_form':u_form , 'p_form': p_form})


def create_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            if User.objects.filter(email=form.cleaned_data['email']):
                messages.error(request, "A user with this email already exist!")
                return render(request, 'registration/signup.html', {'form':form })
            form.save()
            # Authenticate and login
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('home')
        
    else:
        form = SignUpForm()
        return render(request, 'registration/signup.html', {'form':form })
    return render(request, 'registration/signup.html', {'form':form })


@login_required(redirect_field_name='home')
def delete_user(request):
    if request.method == 'POST':
        user = get_object_or_404(User, pk=request.user.id)
        user.delete()
        messages.success(request, 'Your account have been deleted!')
        return redirect('home')
    return render(request, 'registration/delete_profile.html')

accounts/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html class="h-100">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'account.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  </head>

  <body class="h-100">
    <div class="d-flex flex-column h-100">
      {% include "navbar.html" %}

      <main class="container-fluid col-md-10 flex-grow-1">
        {% if messages %}
          {% for message in messages  %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
          {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}

      </main>

      {% include "footer.html" %}
    </div>
  </body>

</html>

accounts/templates/footer.html
<footer class="navbar navbar-expand-lg bg-primary">
    <div class="container-fluid col-md-10">
            <div class="text-white"><small>&#9400; {% now "Y" %} Antoni</small></div>
            <div class=" text-right text-white">
                <a class="icon-link link-light me-2" href="https://github.com/tonivet" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                </svg>
                </a>
                <a class="icon-link link-light" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                </svg>
                </a>
            </div> 
    </div>
</footer>

accounts/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<dev class"mt-5">
    <div class="d-flex justify-content-center">
        <img class="img-fluid" src="{% static "media/welcome.png" %}">
    </div>
</dev>  
{% endblock %}

accounts/templates/navbar.html
<nav class="navbar navbar-dark navbar-expand-lg bg-primary">
  <div class="container-fluid col-md-10">
    <a class="navbar-brand text-white" href="{% url "home" %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            <a href="{% url 'profile' %}" class="nav-item nav-link active ms-auto text-white">Profile</a>
              <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
              <button class="nav-link active ms-auto text-white"  type="submit">Log Out</button>
              </form>
          {% else  %}
            <a href="{% url "signup" %}" class="nav-item nav-link active ms-auto text-white">Sign Up</a>
            <a href="{% url 'login' %}" class="nav-item nav-link active ms-auto text-white">Login</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>

accounts/templates/profile.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<h2> Profile info:</h2>
<div class="d-flex">
    <div class="me-2 align-content-center">
        <img class="profile-pic" src="{{user.userprofile.image.url}}">
    </div>
    <div class="align-content-center ">
        <p  class="m-0">First name: {{ user.first_name | default_if_none:""  }} </p>
        <p  class="m-0">Last name: {{ user.last_name | default_if_none:"" }}</p>
        <p  class="m-0">Gender: {{ user.userprofile.get_sex_display | default_if_none:"" }}</p>
        <p  class="m-0">City: {{ user.userprofile.city | default_if_none:"" }}</p>
        <p  class="m-0">Country: {{ user.userprofile.country | default_if_none:"" }}</p>
        <p  class="m-0">Email: {{ user.email | default_if_none:"" }}</p>
        <p  class="m-0"><a href="{% url 'edit-profile' %}" class="text-decoration-none">Edit profile</a></p>
        <p  class="m-0"><a href="{% url 'password_change' %}" class="text-decoration-none">Change password</a></p>
        <p  class="m-0"><a href="{% url 'delete-profile' %}" class="text-decoration-none">Delete profile</a></p>
    </div>
</div>

{% endblock %}